---
services:
  gotify:
    image: gotify/server
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
    volumes:
      - './gotify_data:/app/data'
    env_file: .env
    networks:
      - gotify

networks:
  gotify:
    name: gotify
    driver: bridge
